<a href="https://colab.research.google.com/github/Radhit2906/Preprocessing/blob/main/decisiontree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Import library numpy, pandas dan scikit-learn
import numpy as np
import pandas as pd
from sklearn import tree

In [ ]:
#Membaca Dataset dari File ke Pandas dataFrame
CobaDataset = pd.read_csv('DatasetCoba1.csv', delimiter=';', header=0)

In [ ]:
CobaDataset.head()

No   Kecamatan  Desil  Prioritas JenisKelamin HubunganKepalaKeluarga  \
0  47737  KOTA KUDUS       1    Normal    Laki-laki        Kepala Keluarga   
1  47738  KOTA KUDUS       1    Normal    Perempuan            Istri/Suami   
2  47739  KOTA KUDUS       1    Normal    Laki-laki                   Anak   
3  47740  KOTA KUDUS       1    Normal    Laki-laki                   Anak   
4  47741  KOTA KUDUS       1    Normal    Laki-laki                   Anak   

             Pekerjaan  Usia2023 SEMBAKO  
0        Pekerja Lepas        40   Tidak  
1  Tidak/Belum Bekerja        39   Tidak  
2  Tidak/Belum Bekerja        16   Tidak  
3  Tidak/Belum Bekerja         8   Tidak  
4  Tidak/Belum Bekerja        19   Tidak

In [ ]:
# Mengubah kelas kolom (penerima sembako)label menjadi unique integer
CobaDataset["SEMBAKO"] = pd.factorize(CobaDataset.SEMBAKO)[0]

In [ ]:
# Mengubah kelas kolom (penerima sembako)label menjadi unique integer
CobaDataset["Pekerjaan"] = pd.factorize(CobaDataset.Pekerjaan)[0]
CobaDataset["Prioritas"] = pd.factorize(CobaDataset.Prioritas)[0]
CobaDataset["JenisKelamin"] = pd.factorize(CobaDataset.JenisKelamin)[0]
CobaDataset["HubunganKepalaKeluarga"] = pd.factorize(CobaDataset.HubunganKepalaKeluarga)[0]

In [ ]:
CobaDataset.head()

No   Kecamatan  Desil   Prioritas  JenisKelamin  HubunganKepalaKeluarga  \
0  47737  KOTA KUDUS       1          0             0                       0   
1  47738  KOTA KUDUS       1          0             1                       1   
2  47739  KOTA KUDUS       1          0             0                       2   
3  47740  KOTA KUDUS       1          0             0                       2   
4  47741  KOTA KUDUS       1          0             0                       2   

   Pekerjaan  Usia2023  SEMBAKO  
0          0        40        0  
1          1        39        0  
2          1        16        0  
3          1         8        0  
4          1        19        0

In [ ]:
print(CobaDataset)

          No   Kecamatan  Desil   Prioritas  JenisKelamin  \
0      47737  KOTA KUDUS       1          0             0   
1      47738  KOTA KUDUS       1          0             1   
2      47739  KOTA KUDUS       1          0             0   
3      47740  KOTA KUDUS       1          0             0   
4      47741  KOTA KUDUS       1          0             0   
...      ...         ...     ...        ...           ...   
27517  75254  KOTA KUDUS       4          0             1   
27518  75255  KOTA KUDUS       4          0             0   
27519  75256  KOTA KUDUS       4          0             0   
27520  75257  KOTA KUDUS       4          0             1   
27521  75258  KOTA KUDUS       4          0             1   

       HubunganKepalaKeluarga  Pekerjaan  Usia2023  SEMBAKO  
0                           0          0        40        0  
1                           1          1        39        0  
2                           2          1        16        0  
3                  

In [ ]:
CobaDataset = CobaDataset.drop(labels="No", axis=1)

In [ ]:
CobaDataset = CobaDataset.drop(labels="Kecamatan", axis=1)

In [ ]:
print(CobaDataset)

       Desil   Prioritas  JenisKelamin  HubunganKepalaKeluarga  Pekerjaan  \
0           1          0             0                       0          0   
1           1          0             1                       1          1   
2           1          0             0                       2          1   
3           1          0             0                       2          1   
4           1          0             0                       2          1   
...       ...        ...           ...                     ...        ...   
27517       4          0             1                       2          1   
27518       4          0             0                       2          1   
27519       4          0             0                       0          1   
27520       4          0             1                       1          1   
27521       4          0             1                       2          2   

       Usia2023  SEMBAKO  
0            40        0  
1            39      

In [ ]:
CobaDataset = CobaDataset.to_numpy()

In [ ]:
print(CobaDataset)

[[ 1  0  0 ...  0 40  0]
 [ 1  0  1 ...  1 39  0]
 [ 1  0  0 ...  1 16  0]
 ...
 [ 4  0  0 ...  1 69  0]
 [ 4  0  1 ...  1 59  0]
 [ 4  0  1 ...  2 29  0]]


In [ ]:
#Membagi Dataset => 80 baris data untuk training dan 20 baris data untuk testing
dataTraining = np.concatenate((CobaDataset[0:100, :], CobaDataset[100:1000, :]),
                              axis=0)
dataTesting = np.concatenate((CobaDataset[1000:2000, :], CobaDataset[2000:15000, :]),
                              axis=0)

In [ ]:
print(dataTraining)
len(dataTraining)

[[ 1  0  0 ...  0 40  0]
 [ 1  0  1 ...  1 39  0]
 [ 1  0  0 ...  1 16  0]
 ...
 [ 2  0  1 ...  2 37  0]
 [ 2  0  1 ...  1 16  0]
 [ 2  0  0 ...  1 14  0]]


1000

In [ ]:
# memecah dataset ke input dan label
inputTraining = dataTraining[:, 0:6]
inputTesting = dataTesting[:, 0:6]
labelTraining = dataTraining[:, 6]
labelTesting = dataTesting[:, 6]

print(labelTraining)
len(labelTraining)

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 1 0 0
 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 

1000

In [ ]:
model = tree.DecisionTreeClassifier()

In [ ]:
# Training Model
model = model.fit(inputTraining, labelTraining)

In [ ]:
#Memprediksi Input Data Testing
hasilPrediksi = model.predict(inputTesting)
print("Label Sebenarnya : ", labelTesting)
print("Hasil Prediksi : ", hasilPrediksi)

Label Sebenarnya :  [0 0 0 ... 0 0 0]
Hasil Prediksi :  [0 0 0 ... 0 0 0]


In [ ]:
#Menghitung Akurasi
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("Prediksi Benar :", prediksiBenar, "data")
print("Prediksi Salah :", prediksiSalah, "data")
print("Akurasi :", prediksiBenar/(prediksiBenar+prediksiSalah) * 100, "%")

Prediksi Benar : 12937 data
Prediksi Salah : 1063 data
Akurasi : 92.40714285714286 %
